name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |bitcoinblank.yml
      run: - name: Setup Dotnet for use with actions
  uses: actions/setup-dotnet@v1.0.0
  with:
    # Version to use. E.g. 2.2.104
    version: v1.00
   - name: - name: Setup Ruby for use with actions
  uses: actions/setup-ruby@v1.0.0
  with:
    # Version range or exact version of a Ruby version to use.
    version: # optional, default is >= 2.4
        echo Add other actions to build,
        echo test, and deploy your project.
